name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js Environment
        uses: actions/setup-node@v2.1.5
      
      - name: Install Dependencies
        run: |
          npm i
      
      - name: Package Electron App
        run: node .
      
      - name: Upload Electron App
        uses: actions/upload-artifact@v2-preview
        with:
          name: ${{ github.event.repository.name }}
          path: cablejs-electron-win32-x64/