name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js Environment
        uses: actions/setup-node@v2.1.5
      
      - name: Install Dependencies
        run: |
          npm i
      
      - name: Package Electron App
        run: node packager.js

      - name: Sign Electron App
        run: |
          & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe' sign /f pfx\emeraldsys_main.pfx /p '${{ secrets.CERTIFICATE_PASS }}' /tr http://timestamp.digicert.com /td sha384 /fd sha384 'cablejs-electron-win32-x64\cablejs-electron.exe'
      
      - name: Upload Electron App
        uses: actions/upload-artifact@v2-preview
        with:
          name: CableJSClient
          path: |
            cablejs-electron-win32-x64/
            cablejs-electron-linux-x64/